prisma/schema.prisma

coupon -> counpon template, user coupon으로 구분 
enum에 스탬프/ 프로모션 추가

refactor: 스키마 수정

---

src/controllers/auth.controller.js
src/controllers/user.controller.js
src/routes/user.routes.js

- 사용자 닉네임 수정 기능과 선호 키워드 저장 기능 추가
- PATCH /api/v1/users/me/nickname: 사용자 닉네임 수정 API 구현
- PATCH /api/v1/users/me/preferences: 선호 키워드 저장/수정 API 구현
- 닉네임 및 선호 키워드 저장 로컬 테스트 완료
- 
- 지역(preferredArea) 필드 수정 API도 분리해서 구현 예정

닉네임 수정 기능과 선호 키워드 저장 기능 구현

---

prisma/schema.prisma
src/app.js
src/config/passport.js
src/controllers/admin.cafe.controller.js
src/controllers/auth.controller.js
src/controllers/auth.kakaoController.js
src/errors/customErrors.js
src/middlewares/authMiddleware.js
src/routes/admin.cafe.routes.js
src/routes/auth.routes.js
src/services/admin.cafe.service.js
src/services/auth.kakao.service.js
src/services/auth.service.js

📌 작업 개요
- 카페 등록/조회/수정 기능 구현 및 로그인/회원가입 시 사장(OWNER) 역할 선택 가능하도록 수정
✅ 작업 상세 내용
- 카페 등록 기능 구현
- 카페 정보 조회 기능 구현
- 카페 정보 수정 기능 구현
- 회원가입 시 CUSTOMER/OWNER 역할 선택 가능하도록 로직 수정
- prisma 스키마에서 users, stores 테이블에 role 필드 제거하고 UserRole 테이블 추가
🔍 테스트 및 확인 사항
- postman로 요청 테스트 완료
🙋 기타 참고 사항
- 카페 삭제 기능은 일단 구현 X
- 카페 운영 시간 등록 및 조회 기능 관련 테이블 추가할 지 고민 중

사장용 카페 CRUD, 로그인 role 추가 

---

prisma/client.js
prisma/schema.prisma
src/app.js
src/services/auth.service.js

app.use(cors(corsOptions));
app.use(express.json());
cors 설정이랑, json 요청 처리 미들웨어 없어졌길래 추가했습니다
스웨거 문서 확인도 기존에 이미 코드가 있었어서 app.js 파일에 다시 수정해두었습니다
http://localhost:3000/api-docs/ 해당 url에서 확인 가능합니다
cafe 테이블에 기존에 bussiness_hours 값이 있으시다면 
UPDATE cafes
SET business_hours = '{}'
where id = (1, 2, 3 ...); 으로 바꾸시면 오류 발생 없을거에요!
오류 발생하신다면 말씀부탁드립니다

cafe테이블 컬럼 수정 및 미들웨어 재수정

---

docs/swagger.yaml
prisma/schema.prisma
src/app.js
src/controllers/admin.cafe.controller.js
src/errors/customErrors.js
src/routes/admin.cafe.routes.js
src/services/admin.cafe.service.js

- 사장 카페 등록 기능 구현 완료
- 카페 기본 정보 등록
- 카페 운영 정보 등록
- 메뉴 등록
- 카페 사진 등록
- 등록 완료 처리 (cafe status: inactive -> active)
- Postman 테스트 완료
- prisma에 cafeMenu 중복 방지 추가

사장 카페 등록 기능 구현 완료

---

docs/swagger.yaml
src/app.js
src/services/auth.service.js
src/services/user.service.js

- swagger 배포 주소 설정 및 오류 해결
- swagger 오류 수정
- 줄리아 파트 Swagger 작동 테스트 완료
- endpoint랑 테스트 데이터 점검해주시면 좋을 것 같아요
- 테스트 할 때는 swagger 서버 주소 'http://localhost:3000/'로 수정해주세요

[fix] swagger 오류 수정

---

src/controllers/admin.cafe.controller.js
src/errors/customErrors.js
src/routes/admin.cafe.routes.js
src/services/admin.cafe.service.js

- 카페 사진 조회, 삭제 기능 구현
- 1~4 단계 별로 카페 등록 기능 구현 완료
- 카페 사진 조회, 삭제 기능 구현
- 로컬 테스트 완료
- 메뉴 등록 기능은 수정 필요할 수 있음
- swagger.docs도 수정할 예정

[feat] 카페 사진 조회, 삭제 기능 구현

---

.gitignore
docs/swagger.yaml
package.json
pnpm-lock.yaml
prisma/migrations/20250728155758_add_qr_code/migration.sql
prisma/schema.prisma
src/controllers/user.controller.js
src/errors/customErrors.js
src/routes/user.routes.js
src/services/auth.service.js
src/services/user.service.js

- QR코드 조회 기능 구현
- http => https로 url 변경
- 회원가입 시 QR코드 자동 발급 로직 추가
- QR코드 조회 시 프론트에 base64 헝식으로 전달
- QR코드 발급 및 조회 테스트 완료
- Swagger 문서에 QR코드 기능 추가 완료, 서버 url 수정 완료
- 카페 등록 기능도 '스탬프 정책 등록'까지 완료 된 후 swagger 문서 추가할 예정

[feat] QR코드 조회 기능 구현

---

src/app.js
src/controllers/seach.controller.js
src/repositories/search.repository.js
src/services/search.service.js

swagger오류로 인한 수정

---

docs/swagger.yaml
src/routes/cafe.routes.js
src/routes/search.routes.js

✅ 작업 상세 내용
스웨거 검수중 오류 수정 및 jwt 인증 상태에서 테스트 검증
🔍 테스트 및 확인 사항
로컬테스트했습니다
🙋 기타 참고 사항
x

스웨거 재작성 및 인증 테스트

---

docs/swagger.yaml
prisma/schema.prisma
src/controllers/challenge.controller.js

**### 📌 작업 개요**
challenge.controller 및 swagger.docs 수정
**### ✅ 작업 상세 내용**
1. getChallengeDetail에서 참여한 매장 정보 조회(joinedCafe) 추가
2. participateInChallenge에도 joinedCafe 추가
3. getChallengeDetail에 이미지 필드 추가
3. Challenge 수정 사항 기반 swagger 수정
**### 🔍 테스트 및 확인 사항**
swagger 웹에서 테스트 완료
**### 🙋 기타 참고 사항**
X

feat: 챌린지 기능 세부 수정

---

docs/swagger.yaml
prisma/migrations/20250730164627_drop_category/migration.sql
prisma/schema.prisma
src/app.js
src/controllers/admin.cafe.controller.js
src/controllers/customer.home.controller.js
src/errors/customErrors.js
src/routes/admin.cafe.routes.js
src/routes/customer.page.routes.js
src/routes/user.routes.js
src/services/admin.cafe.service.js
src/services/auth.service.js
src/services/customer.home.service.js
src/services/point.service.js

- 자주가는 동네 에러 수정
- 약관 기능 JWT인증 생략
- 온보딩 필드 수정
- JWT 인증 기능 수정
- 해당 기능 테스트 완료
- X

[fix] 자주가는 동네 에러 수정, 약관 기능 인증 생략

---

docs/swagger.yaml
package.json
pnpm-lock.yaml
prisma/schema.prisma
src/controllers/stamp.controller.js
src/routes/stamp.routes.js

1. 스탬프 세부 기능 수정 및 추가
2. relation 오류 수정
**### ✅ 작업 상세 내용**
1. getMyStampBooks에서 image 추가
2. getStampBookDetail에서 만료 여부 조회 추가
3. Extendstampbook에서 소멸 임박 여부 조회 후 연장 가능
5. convertStampToPoint에서 1스탬프당 2포인트로 수정
6. 스탬프 환전 취소 불가에 따라 기능 5 주석 처리
7. 스탬프 히스토리 조회 (환전 완료된 스탬프북) 기능 추가
8. 총 스탬프 수 조회 기능 추가
9. 루피 레벨 조회 기능 추가
10. Swagger 수정
11. Relation 오류 수정
**### 🔍 테스트 및 확인 사항**
**### 🙋 기타 참고 사항**

feat/fix: 스탬프 세부 기능 수정 및 추가, relation 오류 수정

---

src/controllers/auth.kakaoController.js

- 카카오 로그인 기능 프론트와 연동 중 에러 수정
- 카카오 컨트롤러 함수 수정

[fix] kakao로그인 함수 수정

---

prisma/schema.prisma
src/services/auth.kakao.service.js

- kakao 소셜 로그인 함수 수정
- kakao 로그인 서비스 함수 수정
- redierect uri 테스트 후 success 확인 
- 프론트랑 실시간 연결 중이라 충돌 안 나면 일단 머지해놓겠습니다..!

[fix] kakao 소셜 로그인 함수 수정

---

src/controllers/customer.home.controller.js
src/errors/customErrors.js
src/services/auth.kakao.service.js
src/services/customer.home.service.js

-  홈화면 조회에 레벨 필드 추가
- 레벨 조회도 가능하게 수정
- 로컬 테스트 완료
- X
- X

[fix] 홈화면 조회에 레벨 필드 추가

---

docs/swagger.yaml
prisma/schema.prisma
src/services/admin.stamp.service.js
src/services/point.service.js

- 스웨거 테스트 오류 해결
- 일부 사진 추가 기능 S3 연결
- swagger 문서 정리
- 로컬 주소로 swagger 테스트 완료
- 일부 사진 추가 기능은 아직 링크로만 저장

swagger 문서 수정 밎 오류 해결

---

docs/swagger.yaml
src/controllers/admin.cafe.controller.js
src/routes/admin.cafe.routes.js
src/services/admin.cafe.service.js
src/services/user.service.js

- 전화번호 저장 기능 구현 에러 수정
- 메뉴 조회 기능 구현
- 전화번호 저장 요청 필드명 수정
- 스탬프 정책 설정 중 리워드 적용할 메뉴 조회 기능 구현
- 로컬 테스트 아직 못함
- X
- 프론트 연동 중이라 일단 머지하고 메뉴 조회 기능 추후에 테스트 예정

[fix] 전화번호 저장 기능 구현 에러 수정, 메뉴 조회 기능 구현

---

docs/swagger.yaml
src/app.js
src/controllers/user.controller.js
src/errors/customErrors.js
src/routes/user.routes.js
src/services/admin.cafe.service.js

- 전화번호 인증 로직 간략화
- 요청 시 전화번호를 전달받아 인증 완료 처리된 것으로 응답만 반환
- 해당 부분 swagger 수정
- 전화번호 인증 기능, 메뉴 조회 기능 로컬 테스트 완료
- X
- X

전화번호 인증 로직 수정

---

src/app.js

chome: 테스트용

---

prisma/schema.prisma
src/repositories/cafe.repository.js

refactor: stampBook 테이블에 제약조건 추가( cafeId_userid)

---

docs/swagger.yaml
src/services/admin.stamp.service.js

- swagger 문서 에러 수정
-  스탬프 정책 수정 로직 추가 확인 
- swagger 사장 회원 탈퇴 api 카테고리 수정
- X
- X
- X

swagger 문서 에러 수정 밎 스탬프 정책 수정 로직 추가 확인 

---

docs/swagger.yaml
prisma/schema.prisma
src/app.js
src/controllers/coupon.controller.js
src/controllers/stamp.controller.js
src/errors/customErrors.js
src/routes/coupon.routes.js
src/services/coupon.service.js

- 스탬프 적립 시 리뷰 알림 자동 생성
- 사장님 쿠폰 생성 API 구현
[스탬프 관련]
- 스탬프 적립 시 review 타입 알림 자동 생성 로직 추가
- 알림 내용: "지금 방금 적립한 스탬프에 대해 리뷰를 작성해보세요 ✍️"
[쿠폰 관련]
- 쿠폰 유형(discount, freeDrink, sizeUp)에 따라 필수값 조건 분기 처리
- 매장 프로모션 쿠폰 생성 (쿠폰 유형, 쿠폰 사용조건, 쿠폰 사용 기한) 
- couponTemplate 모델 기반 DB 저장
- 스탬프 적립 시 알림 자동 생성 확인 (알림 테이블 insert 확인)
- Swagger 문서 반영 완료

스탬프 적립 시 리뷰 알림 자동 생성 및 사장님 쿠폰 생성 API 구현

---

package.json
pnpm-lock.yaml
src/app.js

- prometheus 설치
- 카페 지표 확인을 위해 설치
- app.js에 prometheus metrics 추가
- X
- X
- 다른 코드에 영향 없음

prometheus 설치(카페 인사이트 제공 기능에 사용)

---

docs/swagger.yaml

- 쿠폰 조회 관련 swagger 들여쓰기 오류 수정
- items, properties 들여쓰기 오류......

fix: 스웨거 들여쓰기 오류 수정

---

docs/swagger.yaml
src/controllers/admin.cafe.controller.js
src/controllers/admin.stamp.controller.js
src/services/admin.cafe.service.js
src/services/admin.stamp.service.js
src/utils/s3.js

- 카페 사진, 스탬프 사진, 메뉴 사진 업로드 함수 수정
- 카페 사진 업로드 기능 수정
- 스탬프 사진 업로드 기능 수정
- 메뉴 사진 업로드 기능 수정
- 머지 후 테스트 예정
- x
- x

[fix] 카페 사진, 스탬프 사진, 메뉴 사진 업로드 함수 수정

---

docker-compose.yml
docs/swagger.yaml
src/repositories/cafe.repository.js
src/services/cafe.service.js
src/services/search.service.js

fix: 스웨거 문서 수정(/cafes/-/bookmark

---

docs/swagger.yaml
insight-automation/logic/sources/insight_monthly.py
insight-automation/run_monthly.py
insight-automation/utils/athena.py
src/controllers/user.controller.js
src/services/dashboard.service.js

-  대시보드 통계 일주일 간격 수정 
- 오늘 기준으로 6일전까지 내역 조회하는 걸로 변경 
- 관련 스웨거도 수정 
- 로컬 테스트 완료
- x
- x

[fix] 대시보드 통계 일주일 간격 수정 

---

docs/swagger.yaml
src/controllers/admin.cafe.controller.js
src/errors/customErrors.js
src/routes/admin.cafe.routes.js
src/services/admin.cafe.service.js

- 메뉴 삭제 기능 구현
- 카페 기본 정보 응답에 이미지id 추가
- 메뉴 삭제 기능 구현
- 카페 기본 정보 응답에 이미지id 추가
- 로컬 테스트 완료
- x
- x

카페 기본 정보 응답에 이미지id 추가, 메뉴 삭제 기능 구현

---

src/controllers/challenge.controller.js

- availablecafes에 이미지 추가
- 참여중인 챌린지는 유저가 챌린지 몇번 참여했는지 데이터 추가
- postman 테스트 완료

fix: 챌린지 상세 조회 로직 수정

---

docs/swagger.yaml

- 스웨거 ref 누락 해결
- 포인트 내역 조회 스웨거 ref 누락 해결
- 로컬 테스트 함
- x

[fix] swagger 수정

---

docs/swagger.yaml

- 이전에서 같은 에러 안 없어져서 또 수정함.
- x
- 로컬에서는 잘 됨..
- x
- x

[fix] 찐막 스웨거 ref 누락 수정

---

docs/swagger.yaml
src/services/admin.cafe.service.js
src/services/admin.stamp.service.js

- 운영시간 로직 수정, 스웨거 에러 해결
- 운영시간 파싱 에러 나던 거 해결
- 스웨거 경로 해결
- 로컬 테스트 완료
- x

운영시간 로직 수정, 스웨거 에러 해결

---

src/controllers/admin.cafe.controller.js
src/services/admin.cafe.service.js

- 운영시간 정보 수정 기능 해결 
- 매일 같은 경우에, 배열로 안 받아도 에러 처리 안 나게 수정 
- 로컬 테스트 완료
- x
- x

운영시간 에러 완전 해결

---

src/services/coupon.service.js

- coupon type 매핑처리
- 스웨거 get 오류로 인해 type 매핑 처리

feat: coupon type 매핑처리

---

docs/swagger.yaml
src/services/admin.cafe.service.js

- 카페id 조회 기능 응답 수정
- cafeStatus도 응답에 추가 
- 로컬 테스트 완료
- (로컬)스웨거 확인 완료
- x
- x

[fix] 카페id 조회 기능 응답 수정

---

docs/swagger.yaml
src/controllers/user.controller.js
src/routes/user.routes.js
src/services/user.service.js

-  sms인증 후 전화번호 수정 기능 구현
-  sms인증 후 전화번호 수정 기능 구현(전화번호 수정 기능)
- 로컬 테스트 o
- x
- x

[feat] sms인증 후 전화번호 수정 기능 구현

---

src/services/user.bookmark.service.js

- 북마크 에러 수정
- 필드명 수정 
- x
- x
- x

[fix] photourl 에러 수정
